[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x", "python39"]

[phases.install]
cmds = [
  "node --version",
  "npm --version", 
  "npm ci --production=false || npm install",
  "npm list || true"
]

[phases.build]
cmds = [
  "npm run build",
  "echo 'PSYBERHERD™ APEX build complete'"
]

[start]
cmd = "npm run start:production"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
NODE_OPTIONS = "--max-old-space-size=512"