[build]
builder = "nixpacks"
buildCommand = "npm ci --production=false || npm install"

[deploy]
startCommand = "npm run start:production"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
region = "us-east4"

[[deploy.services]]
name = "psyberherd-apex-sniper"
numReplicas = 1
runtime = "node"

[deploy.services.env]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"