name: Deploy to Railway

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        
    - name: Install dependencies
      run: npm ci || npm install
      
    - name: Run tests
      run: npm test
      
    - name: Validate platform
      run: npm run validate

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        
    - name: Install Railway CLI
      run: npm install -g @railway/cli
      
    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        if [ -n "$RAILWAY_TOKEN" ]; then
          railway up --service webdevelopment
        else
          echo "RAILWAY_TOKEN not configured - skipping deployment"
          echo "Please add RAILWAY_TOKEN to GitHub Secrets to enable deployment"
        fi
        
    - name: Health Check
      if: success()
      run: |
        echo "Waiting for deployment to stabilize..."
        sleep 30
        curl -f https://webdevelopment-production-023f.up.railway.app/health || echo "Health check pending - service may still be starting"